# # -*- coding: utf-8 -*-
# """파이썬 문제풀이.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1I_HZsAspaKZeBt-aDZJcA1cQqfrX_tzb
# """

# #거스름돈 a원이 있습니다. 500원, 100원, 50원, 10원 동전을 활용하여 해당 거스름돈을 최소한의 동전 개수로 거슬러 주세요.
# #예를 들어, 650원일 경우, 10원 65개도 가능하지만 500원 1개, 100원 1개, 50원 1개가 더 적으므로 이것이 답입니다.
# a = 650
# b = a // 500
# c = (a%500)//100
# d = (a % 100) // 50
# e = (a % 50) // 10

# print(f"{b} {c} {d} {e}")

# #세자리 정수 a가 있다 합시다. a의 모든 자릿수의 합을 구하세요. 예를 들어, a가 123라면 6가 됩니다.
# a = 171
# b = a // 100
# c = (a % 100) // 10
# e = (a % 100) % 10
# print(b+c+e)

# # 두 숫자 바꾸기(swap)
# # 숫자 두 개가 변수 a, b에 저장되어 있습니다. a와 b에 저장된 값을 바꾸어 출력해보세요.
# # 예를 들어, a에 5가 들어있고 b에 3이 들어있으면, a에는 이제 3. b에는 이제 5가 들어가야 합니다.
# a, b = map(int, input().split())
# print(f"{a} {b}")
# temp = a
# a = b
# b = temp
# print(f"{a} {b}")

# """ 삼성전자의 주가가 175,000원이고, SK하이닉스의 주가가 950,000원이라고 가정합니다.
# 어떤 투자자가 삼성전자 50주와 SK하이닉스 20주를 보유하고 있을 때,
# 이 투자자의 주식 총액을 계산하여 출력하는 프로그램을 작성하세요."""

# samsung = 175000
# SK = 950000
# print(f"주식 총액 {samsung * 50} + {SK * 20} = {(samsung * 50) + (SK * 20)}")

# """문제 1의 상황에서 삼성전자의 주가가 4%, SK하이닉스의 주가가 7% 하락했습니다.
# 이때 발생한 총 손실액이 얼마인지 계산하여 출력하세요. (단, 손실액은 양수로 출력합니다.)"""

# sam = 175000
# sk = 950000

# sam_loss = sam * 0.04 * 50
# sk_loss = sk * 0.07 * 20
# total = (sam_loss + sk_loss)
# print(f"총 손실액 : {int(total)}")

# """- 정수 x = 50이 주어졌습니다. 비트 시프트 연산자만을 사용하여 다음을 계산하세요.
# 1. x 에 4를 곱한 값
# 2. x 를 8로 나눈 몫"""
# x = 50
# print(x << 2)
# print(x >> 3)

# """- 변수 x에 ‘SKSAMSUNG’이 저장되어 있습니다. 문자열 인덱싱, 슬라이싱을 활용하여
# - SK SAMSUNG 으로 만들어 출력하세요."""
# x = "SKSAMSUNG"
# print(f"{x[0:2]} {x[2:]}")

# """변수 phone에 “010-1234-5678”이 저장되어 있습니다. 슬라이싱과 문자열 연결을 활용하여 중간 번호를 ****로 변경한 뒤 출력하세요.
# 변수 file_name에 “report.pdf”가 저장되어 있습니다. 슬라이싱을 사용하여 파일명(report)은 그대로 두고, 확장자만 .png로 바꿔서  출력하세요."""

# phone = "010-1234-5678"
# file_name = "report.pdf"

# p_copy = phone[:4]+"****"+phone[8:]
# f_copy = file_name[:7]+"png"

# print(f"{p_copy} {f_copy}")

# """전화번호가 “01012345678”과 같이 저장되어 있습니다.
# 슬라이싱을 사용하여 “010-1234-5678” 형태로 저장하여 출력하세요."""
# p = "01012345678"
# pp = p[:3]+'-'+p[3:7]+"-"+p[7:]
# print(pp)

# """- 영수증 카드 번호를 마스킹 해야합니다. 맨 마지막 4글자만 표시가 되고, 나머지 글자는 *으로 처리되어야 합니다.
# - 데이터 : card_number = “1234-5678-9012-3456”
# - 출력 결과
# - 결제 카드 : ****-****-****-3456"""

# card_number = "1234-5678-9012-3456"
# print(f"****-****-****-{card_number[15:]}")

# """- 이름의 공백을 제거하고, 성과 이름 사이에 공백을 한 칸 넣어 출력하세요.
# - 데이터 : raw_name = “    P ark  gu n  woo”
# - 출력 결과
# - 성 : PARK   /    이름 : GUNWOO"""

# raw_name = "    P ark  gu n  woo"
# raw_name = raw_name.strip()
# raw_name = raw_name.replace(" ", "")
# print(f"성 : {raw_name[:4].upper()} / 이름 : {raw_name[4:].upper()}")

# """- 파일 제목을 다음과 같이 가공하여 출력하세요.
# - 데이터 : file_info = “20260316_test_report.pdf”
# - 출력 결과
# # 작성일 : 2026년 03월 16일
# # 확장자 : PDF 문서"""
# file_info = "20260316_test_report.pdf"
# print(f"작성일 : {file_info[:4]}년 {file_info[4:6]}월 {file_info[6:8]}일")
# print(f"확장자 : {file_info[-3:].upper()} 문서")

# """입력한 문자열 중에서 처음 2글자와 마지막 2글자를 추출한 후
# 이를 합쳐 출력하는 프로그램을 작성하세요."""
# a = str(input())
# sum = a[:2]+a[-2:]
# print(sum)

# """- 첫 줄에 특수 기호 2개를 입력하고 다음 줄에 문자열을 입력 받으세요.
# - 특수 기호 2개 사이에 문자열을 추가하는 프로그램을 작성하세요."""

# a = input()
# b = input()
# sum = a[0]+b+a[1]
# print(f"{sum}")

# """case

# abc -> def

# xyz -> abc

# fff -> iii"""
# a = input()
# for i in a:
#   print(chr((ord(i) - ord('a') + 3) % 26 + ord('a')), end='')

# """점수를 입력받아 90점 이상이면 A,
# 80~89 사이이면 B,
# 70 ~ 79 사이이면 C,
# 그 이하는 F를 출력하는 프로그램을 작성하세요."""

# score = int(input())
# if score >= 90:
#   print('A')
# elif score <= 89 or 80 <= score:
#   print('B')
# elif score <= 79 or 70 <= score:
#   print('C')
# else:
#   print('F')

# """세 숫자를 입력받아, 가장 큰 수를 출력하는 프로그램을 작성하세요."""
# a, b, c = map(int, input().split())
# if a > b and a > c:
#   print(a)
# elif b > a and b > c:
#   print(b)
# else:
#   print(c)

# """두 명의 사용자(A, B)로부터 "가위", "바위", "보" 중 하나를 입력받습니다.
# 누가 이겼는지, 혹은 비겼는지 판정하는 프로그램을 만드세요.

# 출력 예시

# A : 가위, B : 보 → A가 이겼습니다."""
# a, b = map(str,input().split())

# if a == '가위':
#   if b == '보':
#     print("A가 이겼습니다.")
#   elif b == '바위':
#     print("B가 이겼습니다.")
#   else:
#     print("비겼습니다.")
# if a == '바위':
#   if b == '가위':
#     print("A가 이겼습니다.")
#   elif b == '보':
#     print("B가 이겼습니다.")
#   else:
#     print("비겼습니다.")
# if a == '보':
#   if b == '바위':
#     print("A가 이겼습니다.")
#   elif b == '가위':
#     print("B가 이겼습니다.")
#   else:
#     print("비겼습니다.")

# a, b = input().split()

# if a == b:
#     print("비겼습니다.")
# elif (a == "가위" and b == "보") or \
#      (a == "바위" and b == "가위") or \
#      (a == "보" and b == "바위"):
#     print("A가 이겼습니다.")
# else:
#     print("B가 이겼습니다.")

# """입력받은 문자가 소문자면 대문자로, 대문자면 소문자로 변환하세요.

# 소문자를 판별하는 함수는 islower() 입니다.

# 출력 예시 : a 반환 결과 : A"""

# a = str(input())
# if a.islower():
#   a = a.upper()
# else:
#   a = a.lower()
# print(a)

# """단어를 앞에서 읽었을 때와 뒤에서 읽었을 때 완벽히 일치하는 것을 팰린드롬이라고 합니다. 단어 하나를 입력 받아 이것이 팰린드롬인지 아닌지 판별하는 프로그램을 작성하세요.

# ```python
# # 결과 예시

# # 입력값 : level

# # level은 팰린드롬인가요? True
# ```"""

# a = str(input())
# if a == a[::-1]:
#   print("True")
# else:
#   print("False")

# """alist = [1, 2, 3, 4, 5, 6]에 대하여
# 맨 마지막 요소 다음에 10을 삽입한 후, alist를 출력하는 프로그램을 작성하시오"""
# alist = [1, 2, 3, 4, 5, 6]
# alist.append(10)
# print(alist)

# """a, b 두 리스트의 연산 결과가 출력 결과와 같도록 프로그램을 작성하세요. """
# a = [7, 6, 5, 4]

# b = [1, 2, 3]
# print(b+a)
# print(a+b+b)
# print(b[:2]+a[:2] * 3)

# """리스트 a = [1,2,3,4,5,6,7,8,9,10]이 있을 때 정수 b를 입력받아,
# b가 리스트 a에 있는지 판별하는 프로그램을 작성하세요."""

# a = [1,2,3,4,5,6,7,8,9,10]

# b = int(input())
# if b in a:
#   print('b가 a에 있습니다.')
# else:
#   print("없습니다.")

# """5명의 학생 점수가 담긴 리스트 score = [70, 60, 55, 90, 85]가 있습니다.
# score에서 최고 점수와 최저 점수, 평균 점수를 출력하세요."""
# score = [70, 60, 55, 90, 85]
# print(f"최고 점수 : {max(score)} / 최저 점수 : {min(score)} / 평균 점수 : {sum(score) / len(score)}")

# """todo 1 : 반복문을 활용하여 입력받은 값을 5번 출력해 봅시다."""
# a = input()
# for i in range(5):
#   print(a, end ='')

# # todo 2 : 정수 하나를 입력받아, 카운트다운 하는 프로그램을 만들어 봅시다.
# a = int(input())
# while a != 0:
#   print(a)
#   a -= 1

# # todo 3 : n!을 반복문을 통해 구현하세요. n!란, 1부터 n까지의 곱을 의미합니다.
# n = int(input())
# sum = 1
# for i in range(1,n+1):
#   sum *= i
# print(sum)

# # todo 4 : 두 리스트의 합집합을 구하세요.

# a = ['비엔나', '치즈', '하원', '중당','오뎅']

# b = ['하원', '비엔나', '윤우']

# print(set(a) | set(b))

# # todo 5 : 두 리스트의 교집합을 구하세요.

# a = ['비엔나', '치즈', '하원', '중당','오뎅']

# b = ['하원', '비엔나', '윤우']

# print(set(a) & set(b))

# # todo 6 : 두 리스트의 차집합을 구하세요.

# a = ['비엔나', '치즈', '하원', '중당','오뎅']

# b = ['하원', '비엔나', '윤우']

# print(set(a) - set(b))

# # todo 7 : 두 리스트의 대칭차집합을 구하세요.

# a = ['비엔나', '치즈', '하원', '중당','오뎅']

# b = ['하원', '비엔나', '윤우']

# print(set(a) ^ set(b))

# rows = 5
# cols = 5
# list  = [[(i+j)%2  for i in range(cols)] for j in range(rows)]
# for rows in list:
#   print(rows)

# rows = 5
# cols = 5
# list = [[1 if i == 0 or i == rows -1 or j == 0 or j == cols -1 else 0 for i in range(cols)] for j in range(rows)]

# for rows in list:
#   print(rows)

# rows = 5
# cols = 5
# list = [[1 if i == j or i + j == 4 else 0 for i in range(cols)] for j in range(rows)]

# for rows in list:
#   print(rows)

# rows = 5
# cols = 5
# list = [[1 if i >= j else 0 for i in range(cols)] for j in range(rows)]

# for rows in list:
#   print(rows)